export const metadata = {
  title: 'Lively Auth|Products',
  description: 'Generated by create next app',
};

export default function ProductDetailLayour({ children }) {
  return (
    <>
      {children}
      <h2 className="mx-auto">Featured Products</h2>
    </>
  );
}
