import Header from '@/components/header';
import Footer from '@/components/footer';
import { Inter } from 'next/font/google';
import './globals.css';
import Link from 'next/link';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: {
    absolute: '',
    default: 'Lively Auth',
    template: '%s | Lively Auth',
  },
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header />
        <Link
          href="/"
          className="underline underline-offset-2 decoration-4 decoration-purple-600 block mt-2"
        >
          Home
        </Link>
        {children}
        <Footer />
      </body>
    </html>
  );
}
